version: 2
updates:
  # npm (pnpm)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    groups:
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        dependency-type: 'development'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'

  # Dev Containers
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '10:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
